yml.person:
  boss: true
  # 日期写法必须为你/区分，或者自己在 additional-spring-configuration-metadata.json文件中定义类型
  birth: 1983/12/14
  age: 39
  # 另一个对象
  pet:
    name: 小黄
    weight: 15
  interests: [抽烟,喝酒,烫头]
  animal:
    - 大象
    - 老虎
    - 狮子
  score:
    chinese: 99
    math: 100
    psychological: 13
  salarys: [20000,180000]
  allPets:
    # key 不能为中文
    dongwu:
      - {name: 小黄,weight: 15} # 行内写法 对象
      - name: 小米
        weight: 8
    zhiwu:
      - name: 富贵竹
        weight: 1.5
      - name: 绿萝
        weight: 1
    other: [{name: 恐龙,weight: 1000000},{name: 小猪,weight: 500}]
yml:
  person:
    # -n 表示 N
    user-name: 张三

