spring:
#  mvc:
#    static-path-pattern: /public/**
  web:
    resources:
      add-mappings: true # 禁用默认的静态资源目录
      cache:
        period: 11000 # 设置缓存策略：静态资源可被静态资源处理器保存的时间（单位为秒），然后浏览器就会默认把静态资源存放这么长时间缓存，不是每静态文件再从服务器获取
  mvc:
    hiddenmethod:
      filter:
        enabled: true # 开启默认的HiddenHttpMethodFilter
    view:
      prefix: static
      suffix: .html
#      static-locations: classpath:/templates/