#server:
#  servlet:
#    context-path: /manage # 设置当前项目名

#spring:
#  mvc:
#    # 默认是 /**
#    static-path-pattern: /staticResource/**
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#server:
#  jetty:
#    accesslog:
#      append: true
#
#  tomcat:
#    accesslog:
#      buffered: true
#
#  undertow:
#    accesslog:
#      enabled: true